# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0029_auto_20171120_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100)),
                ('series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.Series')),
            ],
        ),
    ]
